name: Deploy Worker
on:
  push:
    branches: ["main"]
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
        cache: "npm"

    - name: Install modules
      run: npm ci

    - name: Prepare
      run: sed -i "s/KV_NAME/{{ secrets.KV_NAME }}/g" wrangler.toml

    - name: Deploy
      env: 
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: npm run deploy
